define(["dizzy/group","dizzy/transformation","sandbox"],function(m,v,w){var n=function(b,a){this.container=$(b);this.groupList=[];this.activeGroupNumber=0;this.options=a||{transformDuration:1E3}};n.prototype={WIDTH:2E3,HEIGHT:1500,load:function(b,a){var c=this,a=a||{};this.container.children().disableTextSelect();this.container.empty().removeClass("hasSVG").svg({loadURL:b,onLoad:function(){c.svg=c.container.svg("get");c.canvas=$("g#canvas");c.canvas.find(".group").each(function(){c.getGroup($(this))});
typeof a.success==="function"&&a.success()}})},serialize:function(){$(this.svg.root()).attr("xmlns","http://www.w3.org/2000/svg");$(".group:empty",this.svg.root()).remove();return this.svg.toSVG()},createGroup:function(){var b=this.getGroup(0),a=$(this.svg.group(b.dom())),b=v.createTransform(b.transformation().matrix().inverse());a.addClass("group");a=new m(a);a.transformation(b);this.groupList.push(a);return a},removeGroup:function(b){for(var a=b.dom().attr("id"),c=0;c<this.groupList.length;c++)if(this.groupList[c].dom().attr("id")==
a){b.dom().remove();this.groupList.splice(c,1);console.log("Group "+a+" removed!");w.publish("dizzy.canvas.group.removed",{id:a});break}},findGroup:function(b){for(var a=0;a<this.groupList.length;++a)if(this.groupList[a]&&this.groupList[a].dom().attr("id")===$(b).attr("id"))return this.groupList[a];var c,b=jQuery(b);b.size()>0&&(c=new m(b[0]),this.groupList.push(c));return c},findGroupById:function(b){for(var a=0;a<this.groupList.length;++a)if(this.groupList[a]&&this.groupList[a].dom().attr("id")===
b)return this.groupList[a]},getGroup:function(b){if(b.dom&&b.transformation)return b;var a;if(b>0)a=this.canvas.find(".group_"+b);else if(b===0)a=this.canvas;return this.findGroup(a||b)},gotoGroup:function(b,a){typeof b!=="number"&&(b=this.getGroup(b));this.activeGroupNumber=b;try{this.current(a)}catch(c){}},centerGroup:function(b,a){typeof b!=="number"&&(b=this.getGroup(b));a=$.extend({scale:1,translate:!1},a);this.transformCanvasTo(b,a)},next:function(){return this.step(1)},previous:function(){if(this.activeGroupNumber!=
0)return this.step(-1)},step:function(b){this.activeGroupNumber+=b;try{this.current()}catch(a){this.activeGroupNumber-=b}return this.activeGroupNumber},visitGroup:function(b,a){for(var c,d=0;d<this.groupList.length;++d)if(this.groupList[d]&&this.groupList[d].dom().attr("id")===b){c=this.groupList[d];break}this.transformCanvasTo(c,a)},transformCanvasTo:function(b,a){var c=this.getGroup(0);if(b!==void 0){var d=b.transformation(),d=v.createTransform(d.matrix());d.inverse();if(b.dom().attr("id")!="canvas")try{var e=
b.dom().children().first(),h=e.prop("localName");if(h=="rect"||h=="image"||h=="ellipse"||h=="line"||h=="text"){var i,j,g,f;switch(h){case "rect":i=e.attr("x");j=e.attr("y");g=e.attr("width");f=e.attr("height");break;case "image":i=e.attr("x");j=e.attr("y");g=e.attr("width");f=e.attr("height");g=g.substring(0,g.length-2);f=f.substring(0,f.length-2);break;case "ellipse":i=e.attr("cx")-e.attr("rx");j=e.attr("cy")-e.attr("ry");g=e.attr("rx")*2;f=e.attr("ry")*2;break;case "line":i=e.attr("x1");j=e.attr("y1");
g=Math.abs(i-e.attr("x2"));f=Math.abs(j-e.attr("y2"));break;case "text":var k=e[0].getBBox();i=k.x;j=k.y;g=k.width;f=k.height}var r=$(document).width(),s=$(document).height(),m=$("svg").attr("viewBox").split(" ",4),t=m[2],u=m[3],o,p;r/s>=t/u?(p=u,o=u/s*r):(o=t,p=t/r*s);var n=e.parent().attr("zoom"),h=n?n:100;h/=100;var l=Math.min(o*h/g,p*h/f);a!=void 0&&a.scale!=void 0&&(l=l<a.scale?l-0.06:a.scale);var x=d.matrix();d.multiply(x.inverse()).translate(-i,-j).multiply(x);var y=d.matrix();d.multiply(y.inverse()).scale(l).multiply(y);
i=(o-g*l)/2;f=(p-f*l)/2;var z=d.matrix();d.multiply(z.inverse()).translate(i,f).multiply(z);var q=e.parent().attr("speed"),q=q?q:1,a=$.extend({duration:parseInt(q*1E3)},a);this.transform(c,d,a);w.publish("dizzy.canvas.group.visited")}}catch(A){alert("errore: "+A.message)}}else throw"Ops! This should not have happened! (o:";},current:function(b){this.getGroup(0);this.transformCanvasTo(this.getGroup(this.activeGroupNumber),b);return this.activeGroupNumber},transform:function(b,a,c){var c=$.extend({complete:function(){},
duration:this.options.transformDuration},c),d=c.duration===void 0?this.options.transformDuration:c.duration;b.transform=a;d<=10?$(b.dom(),this.svg.root()).attr("transform",a.toString()):$(b.dom(),this.svg.root()).animate({svgTransform:a.toString()},c)},transformSVGanimation:function(b,a,c){var c=$.extend({complete:function(){},duration:this.options.transformDuration},c),c=c.duration===void 0?this.options.transformDuration:c.duration,d=a.matrix(),e=b.transform.matrix(),h=document.getElementById("canvTranslate"),
i=document.getElementById("canvRotate"),j=document.getElementById("canvScale");h.setAttribute("dur",c/1E3+"s");i.setAttribute("dur",c/1E3+"s");j.setAttribute("dur",c/1E3+"s");console.log(e);var g=e.e,f=e.f,k=Math.sqrt(Math.pow(e.a,2)+Math.pow(e.b,2)),e=Math.atan(e.c/e.d);console.log("canv transX: "+g);console.log("canv transY: "+f);console.log("canv scale: "+k);console.log("canv rotate: "+e);h.setAttribute("from",g+","+f);i.setAttribute("from",-e*180/Math.PI);j.setAttribute("from",k);console.log(d);
g=d.e;f=d.f;k=Math.sqrt(Math.pow(d.a,2)+Math.pow(d.b,2));e=Math.atan(d.c/d.d);console.log("transX: "+g);console.log("transY: "+f);console.log("scale: "+k);console.log("rotate: "+e);h.setAttribute("to",g+","+f);i.setAttribute("to",-e*180/Math.PI);j.setAttribute("to",k);h.beginElement();i.beginElement();j.beginElement();b.transform=a;setTimeout(function(){$("#canvas").attr("transform","matrix("+d.a+","+d.b+","+d.c+","+d.d+","+d.e+","+d.f+")")},c+100)},toViewboxCoordinates:function(b,a){var c=this.svg.root().createSVGPoint();
c.x=b.x;c.y=b.y;var d=this.svg.root().getScreenCTM();a||(d=d.inverse());return c.matrixTransform(d)},toCanvasCoordinates:function(b,a){var c=this.svg.root().createSVGPoint();c.x=b.x;c.y=b.y;var d=this.svg.root().getScreenCTM(),e=this.getGroup(0).transformation().matrix(),d=d.multiply(e);a||(d=d.inverse());return c.matrixTransform(d)},vectorTranslate:function(b,a){var a=a||{},a=$.extend({ignoreCanvas:!1,targetNode:void 0,inverseMatrix:!1},a),c=this.svg.root().createSVGPoint();c.x=b.x;c.y=b.y;var d;
if(a.targetNode)d=a.targetNode.getCTM().inverse();else{d=this.svg.root().getScreenCTM();var e=this.getGroup(0).transformation().matrix();if(!a.ignoreCanvas)d=d.multiply(e),a.inverseMatrix=!0;a.inverseMatrix&&(d=d.inverse())}c=c.matrixTransform(d);return{x:c.x,y:c.y}},pathCounter:0,addPathNumber:function(b,a){a===void 0&&(a=++pathCounter);b.dom().addClass("group_"+a)},removePathNumber:function(b,a){a===void 0&&(a=[]);typeof a==="number"&&(a=[a]);for(var c=0;c<a.length;++c)b.dom().removeClass("group_"+
a[c])},getFillColor:function(){return $("#tool-input-color-fill").val()},getStrokeColor:function(){return $("#tool-input-color-stroke").val()}};return n});