/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2011-11-07
 @link    http://jscolor.com
*/
var jscolor={dir:"",bindClass:"color",binding:!0,preloading:!0,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var b=jscolor.detectDir();jscolor.dir=b!==!1?b:"jscolor/"}return jscolor.dir},detectDir:function(){for(var b=location.href,e=document.getElementsByTagName("base"),a=0;a<e.length;a+=1)if(e[a].href)b=e[a].href;e=document.getElementsByTagName("script");for(a=
0;a<e.length;a+=1)if(e[a].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(e[a].src))return b=(new jscolor.URI(e[a].src)).toAbsolute(b),b.path=b.path.replace(/[^\/]+$/,""),b.query=null,b.fragment=null,b.toString();return!1},bind:function(){for(var b=RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),e=document.getElementsByTagName("input"),a=0;a<e.length;a+=1){var m;if(!e[a].color&&e[a].className&&(m=e[a].className.match(b))){if(m[3])try{eval("prop="+m[3])}catch(v){}e[a].color=new jscolor.color(e[a],
{})}}},preload:function(){for(var b in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(b)&&jscolor.loadImage(b)},images:{pad:[181,101],sld:[16,101],cross:[15,15],arrow:[7,11]},imgRequire:{},imgLoaded:{},requireImage:function(b){jscolor.imgRequire[b]=!0},loadImage:function(b){if(!jscolor.imgLoaded[b])jscolor.imgLoaded[b]=new Image,jscolor.imgLoaded[b].src=jscolor.getDir()+b},fetchElement:function(b){return typeof b==="string"?document.getElementById(b):b},addEvent:function(b,e,a){b.addEventListener?
b.addEventListener(e,a,!1):b.attachEvent&&b.attachEvent("on"+e,a)},fireEvent:function(b,e){if(b)if(document.createEvent){var a=document.createEvent("HTMLEvents");a.initEvent(e,!0,!0);b.dispatchEvent(a)}else if(document.createEventObject)a=document.createEventObject(),b.fireEvent("on"+e,a);else if(b["on"+e])b["on"+e]()},getElementPos:function(b){var e=b,a=0,m=0;if(e.offsetParent){do a+=e.offsetLeft,m+=e.offsetTop;while(e=e.offsetParent)}for(;(b=b.parentNode)&&b.nodeName.toUpperCase()!=="BODY";)a-=
b.scrollLeft,m-=b.scrollTop;return[a,m]},getElementSize:function(b){return[b.offsetWidth,b.offsetHeight]},getRelMousePos:function(b){var e=0,a=0;if(!b)b=window.event;if(typeof b.offsetX==="number")e=b.offsetX,a=b.offsetY;else if(typeof b.layerX==="number")e=b.layerX,a=b.layerY;return{x:e,y:a}},getViewPos:function(){return typeof window.pageYOffset==="number"?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,document.body.scrollTop]:
document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return typeof window.innerWidth==="number"?[window.innerWidth,window.innerHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?
[document.documentElement.clientWidth,document.documentElement.clientHeight]:[0,0]},URI:function(b){function e(a){for(var b="";a;)if(a.substr(0,3)==="../"||a.substr(0,2)==="./")a=a.replace(/^\.+/,"").substr(1);else if(a.substr(0,3)==="/./"||a==="/.")a="/"+a.substr(3);else if(a.substr(0,4)==="/../"||a==="/..")a="/"+a.substr(4),b=b.replace(/\/?[^\/]*$/,"");else if(a==="."||a==="..")a="";else{var e=a.match(/^\/?[^\/]*/)[0],a=a.substr(e.length);b+=e}return b}this.authority=this.scheme=null;this.path=
"";this.fragment=this.query=null;this.parse=function(a){a=a.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=a[3]?a[2]:null;this.authority=a[5]?a[6]:null;this.path=a[7];this.query=a[9]?a[10]:null;this.fragment=a[12]?a[13]:null;return this};this.toString=function(){var a="";this.scheme!==null&&(a=a+this.scheme+":");this.authority!==null&&(a=a+"//"+this.authority);this.path!==null&&(a+=this.path);this.query!==null&&(a=a+"?"+this.query);this.fragment!==
null&&(a=a+"#"+this.fragment);return a};this.toAbsolute=function(a){var a=new jscolor.URI(a),b=new jscolor.URI;if(a.scheme===null)return!1;if(this.scheme!==null&&this.scheme.toLowerCase()===a.scheme.toLowerCase())this.scheme=null;this.scheme!==null?(b.scheme=this.scheme,b.authority=this.authority,b.path=e(this.path),b.query=this.query):(this.authority!==null?(b.authority=this.authority,b.path=e(this.path),b.query=this.query):(this.path===""?(b.path=a.path,b.query=this.query!==null?this.query:a.query):
(this.path.substr(0,1)==="/"?b.path=e(this.path):(b.path=a.authority!==null&&a.path===""?"/"+this.path:a.path.replace(/[^\/]+$/,"")+this.path,b.path=e(b.path)),b.query=this.query),b.authority=a.authority),b.scheme=a.scheme);b.fragment=this.fragment;return b};b&&this.parse(b)},color:function(b,e){function a(k,b,a){if(k===null)return[a,a,a];var c=Math.floor(k),d=a*(1-b),k=a*(1-b*(c%2?k-c:1-(k-c)));switch(c){case 6:case 0:return[a,k,d];case 1:return[k,a,d];case 2:return[d,a,k];case 3:return[d,k,a];case 4:return[k,
d,a];case 5:return[a,d,k]}}function m(k,a){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),sldM:document.createElement("div"),btn:document.createElement("div"),btnS:document.createElement("span"),btnT:document.createTextNode(c.pickerCloseText)};for(var i=0;i<jscolor.images.sld[1];i+=
4){var e=document.createElement("div");e.style.height="4px";e.style.fontSize="1px";e.style.lineHeight="0";jscolor.picker.sld.appendChild(e)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);
jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);jscolor.picker.boxB.appendChild(jscolor.picker.box)}var d=jscolor.picker;d.box.onmouseup=d.box.onmouseout=function(){b.focus()};d.box.onmousedown=function(){p=!0};d.box.onmousemove=function(a){if(q||r)q&&z(a),r&&A(a),document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges(),t()};d.padM.onmouseup=d.padM.onmouseout=function(){q&&(q=!1,jscolor.fireEvent(f,
"change"))};d.padM.onmousedown=function(a){q=!0;z(a);t()};d.sldM.onmouseup=d.sldM.onmouseout=function(){r&&(r=!1,jscolor.fireEvent(f,"change"))};d.sldM.onmousedown=function(a){r=!0;A(a);t()};i=v(c);d.box.style.width=i[0]+"px";d.box.style.height=i[1]+"px";d.boxB.style.position="absolute";d.boxB.style.clear="both";d.boxB.style.left=k+"px";d.boxB.style.top=a+"px";d.boxB.style.zIndex=c.pickerZIndex;d.boxB.style.border=c.pickerBorder+"px solid";d.boxB.style.borderColor=c.pickerBorderColor;d.boxB.style.background=
c.pickerFaceColor;d.pad.style.width=jscolor.images.pad[0]+"px";d.pad.style.height=jscolor.images.pad[1]+"px";d.padB.style.position="absolute";d.padB.style.left=c.pickerFace+"px";d.padB.style.top=c.pickerFace+"px";d.padB.style.border=c.pickerInset+"px solid";d.padB.style.borderColor=c.pickerInsetColor;d.padM.style.position="absolute";d.padM.style.left="0";d.padM.style.top="0";d.padM.style.width=c.pickerFace+2*c.pickerInset+jscolor.images.pad[0]+jscolor.images.arrow[0]+"px";d.padM.style.height=d.box.style.height;
d.padM.style.cursor="crosshair";d.sld.style.overflow="hidden";d.sld.style.width=jscolor.images.sld[0]+"px";d.sld.style.height=jscolor.images.sld[1]+"px";d.sldB.style.display=c.slider?"block":"none";d.sldB.style.position="absolute";d.sldB.style.right=c.pickerFace+"px";d.sldB.style.top=c.pickerFace+"px";d.sldB.style.border=c.pickerInset+"px solid";d.sldB.style.borderColor=c.pickerInsetColor;d.sldM.style.display=c.slider?"block":"none";d.sldM.style.position="absolute";d.sldM.style.right="0";d.sldM.style.top=
"0";d.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+c.pickerFace+2*c.pickerInset+"px";d.sldM.style.height=d.box.style.height;try{d.sldM.style.cursor="pointer"}catch(j){d.sldM.style.cursor="hand"}d.btn.style.display=c.pickerClosable?"block":"none";d.btn.style.position="absolute";d.btn.style.left=c.pickerFace+"px";d.btn.style.bottom=c.pickerFace+"px";d.btn.style.padding="0 15px";d.btn.style.height="18px";d.btn.style.border=c.pickerInset+"px solid";(function(){var a=c.pickerInsetColor.split(/\s+/);
d.btn.style.borderColor=a.length<2?a[0]:a[1]+" "+a[0]+" "+a[0]+" "+a[1]})();d.btn.style.color=c.pickerButtonColor;d.btn.style.font="12px sans-serif";d.btn.style.textAlign="center";try{d.btn.style.cursor="pointer"}catch(g){d.btn.style.cursor="hand"}d.btn.onmousedown=function(){c.hidePicker()};d.btnS.style.lineHeight=d.btn.style.height;switch(n){case 0:var h="../../img/jscolor_hs.png";break;case 1:h="../../img/jscolor_hv.png"}d.padM.style.backgroundImage="url('"+jscolor.getDir()+"../../img/jscolor_cross.gif')";
d.padM.style.backgroundRepeat="no-repeat";d.sldM.style.backgroundImage="url('"+jscolor.getDir()+"../../img/jscolor_arrow.gif')";d.sldM.style.backgroundRepeat="no-repeat";d.pad.style.backgroundImage="url('"+jscolor.getDir()+h+"')";d.pad.style.backgroundRepeat="no-repeat";d.pad.style.backgroundPosition="0 0";B();C();jscolor.picker.owner=c;document.getElementsByTagName("body")[0].appendChild(d.boxB)}function v(a){return[2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[0]+(a.slider?2*a.pickerInset+2*
jscolor.images.arrow[0]+jscolor.images.sld[0]:0),a.pickerClosable?4*a.pickerInset+3*a.pickerFace+jscolor.images.pad[1]+a.pickerButtonHeight:2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[1]]}function B(){switch(n){case 0:var b=1;break;case 1:b=2}jscolor.picker.padM.style.backgroundPosition=c.pickerFace+c.pickerInset+Math.round(c.hsv[0]/6*(jscolor.images.pad[0]-1))-Math.floor(jscolor.images.cross[0]/2)+"px "+(c.pickerFace+c.pickerInset+Math.round((1-c.hsv[b])*(jscolor.images.pad[1]-1))-Math.floor(jscolor.images.cross[1]/
2))+"px";b=jscolor.picker.sld.childNodes;switch(n){case 0:for(var l=a(c.hsv[0],c.hsv[1],1),i=0;i<b.length;i+=1)b[i].style.backgroundColor="rgb("+l[0]*(1-i/b.length)*100+"%,"+l[1]*(1-i/b.length)*100+"%,"+l[2]*(1-i/b.length)*100+"%)";break;case 1:var e,d=[c.hsv[2],0,0],i=Math.floor(c.hsv[0]),j=i%2?c.hsv[0]-i:1-(c.hsv[0]-i);switch(i){case 6:case 0:l=[0,1,2];break;case 1:l=[1,0,2];break;case 2:l=[2,0,1];break;case 3:l=[2,1,0];break;case 4:l=[1,2,0];break;case 5:l=[0,2,1]}for(i=0;i<b.length;i+=1)e=1-1/
(b.length-1)*i,d[1]=d[0]*(1-e*j),d[2]=d[0]*(1-e),b[i].style.backgroundColor="rgb("+d[l[0]]*100+"%,"+d[l[1]]*100+"%,"+d[l[2]]*100+"%)"}}function C(){switch(n){case 0:var a=2;break;case 1:a=1}jscolor.picker.sldM.style.backgroundPosition="0 "+(c.pickerFace+c.pickerInset+Math.round((1-c.hsv[a])*(jscolor.images.sld[1]-1))-Math.floor(jscolor.images.arrow[1]/2))+"px"}function u(){return jscolor.picker&&jscolor.picker.owner===c}function D(){f!==b&&c.importColor()}function z(a){var b=jscolor.getRelMousePos(a),
a=b.x-c.pickerFace-c.pickerInset,b=b.y-c.pickerFace-c.pickerInset;switch(n){case 0:c.fromHSV(a*(6/(jscolor.images.pad[0]-1)),1-b/(jscolor.images.pad[1]-1),null,w);break;case 1:c.fromHSV(a*(6/(jscolor.images.pad[0]-1)),null,1-b/(jscolor.images.pad[1]-1),w)}}function A(a){a=jscolor.getRelMousePos(a).y-c.pickerFace-c.pickerInset;switch(n){case 0:c.fromHSV(null,null,1-a/(jscolor.images.sld[1]-1),x);break;case 1:c.fromHSV(null,1-a/(jscolor.images.sld[1]-1),null,x)}}function t(){if(c.onImmediateChange)if(typeof c.onImmediateChange===
"string")eval(c.onImmediateChange);else c.onImmediateChange(c)}this.adjust=this.required=!0;this.hash=!1;this.slider=this.caps=!0;this.styleElement=this.valueElement=b;this.onImmediateChange=null;this.hsv=[0,0,1];this.rgb=[1,1,1];this.pickerOnfocus=!0;this.pickerMode="HSV";this.pickerPosition="bottom";this.pickerSmartPosition=!0;this.pickerButtonHeight=20;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=10;this.pickerFaceColor="ThreeDFace";this.pickerBorder=
1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDHighlight ThreeDHighlight ThreeDShadow";this.pickerZIndex=1E4;for(var o in e)e.hasOwnProperty(o)&&(this[o]=e[o]);this.hidePicker=function(){u()&&(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(){if(!u()){var a=jscolor.getElementPos(b),c=jscolor.getElementSize(b),i=jscolor.getViewPos(),
e=jscolor.getViewSize(),d=v(this),j,g,h;switch(this.pickerPosition.toLowerCase()){case "left":j=1;g=0;h=-1;break;case "right":j=1;g=0;h=1;break;case "top":j=0;g=1;h=-1;break;default:j=0,h=g=1}var f=(c[g]+d[g])/2,a=this.pickerSmartPosition?[-i[j]+a[j]+d[j]>e[j]?-i[j]+a[j]+c[j]/2>e[j]/2&&a[j]+c[j]-d[j]>=0?a[j]+c[j]-d[j]:a[j]:a[j],-i[g]+a[g]+c[g]+d[g]-f+f*h>e[g]?-i[g]+a[g]+c[g]/2>e[g]/2&&a[g]+c[g]-f-f*h>=0?a[g]+c[g]-f-f*h:a[g]+c[g]-f+f*h:a[g]+c[g]-f+f*h>=0?a[g]+c[g]-f+f*h:a[g]+c[g]-f-f*h]:[a[j],a[g]+
c[g]-f+f*h];m(a[j],a[g])}};this.importColor=function(){if(f)if(this.adjust)!this.required&&/^\s*$/.test(f.value)?(f.value="",h.style.backgroundColor=h.jscStyle.backgroundColor,h.style.color=h.jscStyle.color,this.exportColor(s|y)):this.fromString(f.value)||this.exportColor();else{if(!this.fromString(f.value,s))h.style.backgroundColor=h.jscStyle.backgroundColor,h.style.color=h.jscStyle.color,this.exportColor(s|y)}else this.exportColor()};this.exportColor=function(a){if(!(a&s)&&f){var b=this.toString();
this.caps&&(b=b.toUpperCase());this.hash&&(b="#"+b);f.value=b}if(!(a&y)&&h)h.style.backgroundColor="#"+this.toString(),h.style.color=0.213*this.rgb[0]+0.715*this.rgb[1]+0.072*this.rgb[2]<0.5?"#FFF":"#000";!(a&x)&&u()&&B();!(a&w)&&u()&&C()};this.fromHSV=function(b,c,e,f){b<0&&(b=0)||b>6&&(b=6);c<0&&(c=0)||c>1&&(c=1);e<0&&(e=0)||e>1&&(e=1);this.rgb=a(b===null?this.hsv[0]:this.hsv[0]=b,c===null?this.hsv[1]:this.hsv[1]=c,e===null?this.hsv[2]:this.hsv[2]=e);this.exportColor(f)};this.fromRGB=function(a,
b,c,e){a<0&&(a=0)||a>1&&(a=1);b<0&&(b=0)||b>1&&(b=1);c<0&&(c=0)||c>1&&(c=1);var a=a===null?this.rgb[0]:this.rgb[0]=a,b=b===null?this.rgb[1]:this.rgb[1]=b,d=c===null?this.rgb[2]:this.rgb[2]=c,f=Math.min(Math.min(a,b),d),c=Math.max(Math.max(a,b),d),g=c-f;g===0?a=[null,0,c]:(a=a===f?3+(d-b)/g:b===f?5+(a-d)/g:1+(b-a)/g,a=[a===6?0:a,g/c,c]);a[0]!==null&&(this.hsv[0]=a[0]);a[2]!==0&&(this.hsv[1]=a[1]);this.hsv[2]=a[2];this.exportColor(e)};this.fromString=function(a,b){var c=a.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);
return c?(c[1].length===6?this.fromRGB(parseInt(c[1].substr(0,2),16)/255,parseInt(c[1].substr(2,2),16)/255,parseInt(c[1].substr(4,2),16)/255,b):this.fromRGB(parseInt(c[1].charAt(0)+c[1].charAt(0),16)/255,parseInt(c[1].charAt(1)+c[1].charAt(1),16)/255,parseInt(c[1].charAt(2)+c[1].charAt(2),16)/255,b),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};
var c=this,n=this.pickerMode.toLowerCase()==="hvs"?1:0,p=!1,f=jscolor.fetchElement(this.valueElement),h=jscolor.fetchElement(this.styleElement),q=!1,r=!1,s=1,y=2,x=4,w=8;jscolor.addEvent(b,"focus",function(){c.pickerOnfocus&&c.showPicker()});jscolor.addEvent(b,"blur",function(){p?p=!1:window.setTimeout(function(){p||(f===b&&c.importColor(),c.pickerOnfocus&&c.hidePicker());p=!1},0)});f&&(o=function(){c.fromString(f.value,s);t()},jscolor.addEvent(f,"keyup",o),jscolor.addEvent(f,"input",o),jscolor.addEvent(f,
"blur",D),f.setAttribute("autocomplete","off"));if(h)h.jscStyle={backgroundColor:h.style.backgroundColor,color:h.style.color};switch(n){case 0:jscolor.requireImage("../../img/jscolor_hs.png");break;case 1:jscolor.requireImage("../../img/jscolor_hv.png")}jscolor.requireImage("../../img/jscolor_cross.gif");jscolor.requireImage("../../img/jscolor_arrow.gif");this.importColor()}};jscolor.install();